name: test

on:
  push:
    branches:
      - main

workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v4

      - name: Setup deno
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "2.3.1"

      - name: Run lint
        run: |
          deno lint

      - name: Check mod.ts
        run: |
          deno check mod.ts

      - name: Run tests
        run: |
          deno test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: suwakei/deno-zhconv