name: test

on:
  push:
    branches:
      - main

workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v4

      - name: Setup deno
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "2.3.1"

      - name: Run test
        run: |
          deno test --coverage
          deno coverage --lcov > coverage.lcov          
      - name: upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}