name: test

on: [push]
workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup deno
      - uses: denoland/setup-deno@main
        with:
          deno-version: "2.3.1"
      - name: Run fmt
        run: |
          deno fmt --check
      - name: Run lint
        run: |
          deno lint
      - name: Check mod.ts
        run: |
          deno check mod.ts
      - name: Run tests
        run: |
          deno test -A